# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Start from a lightweight Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY llms_mcp_server.py ./

# Expose no ports (stdio transport)

# Default command
CMD ["python", "llms_mcp_server.py"]
